<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\JobCategory;
use Illuminate\Support\Str;

class JobCategorySeeder extends Seeder
{
    public function run(): void
    {
        $categories = [
            'Engineering & Technical',
            'Automation',
            'Instrumentation',
            'Embedded Systems',
            'Industrial Robotics',
            'PLC & SCADA',
            'IoT',
            'VLSI',
            'Electronics',
            'Electrical Engineering',
            'Mechanical Engineering',
            'Production Engineering',
            'Manufacturing',
            'Quality Control',
            'Quality Assurance',
            'Maintenance',
            'Service Engineering',
            'Field Service',
            'Project Engineering',
            'Renewable Energy',
            'Solar Energy',
            'EV (Electric Vehicle)',
            'HVAC',
            'BMS (Building Management Systems)',
            'ELV Systems',
            'MEP',
            'Fire & Safety',
            'Oil & Gas',
            'Marine Engineering',
            'Ship Maintenance',
            'Civil Engineering',
            'Construction',
            'BIM',
            'Interior Design',
            'Architecture',
            'Quantity Surveying',
            'Information Technology',
            'Software Development',
            'Full Stack Development',
            'Frontend Development',
            'Backend Development',
            'Mobile App Development',
            'DevOps',
            'Cloud Computing',
            'Cyber Security',
            'Networking',
            'Linux Administration',
            'Windows Administration',
            'Azure',
            'AWS',
            'Google Cloud',
            'Database Administration',
            'AI & Machine Learning',
            'Data Science',
            'Data Analytics',
            'Business Intelligence',
            'Software Testing (QA)',
            'UI/UX Design',
            'Web Design',
            'Digital & Creative',
            'Digital Marketing',
            'Performance Marketing',
            'SEO',
            'SEM',
            'Social Media Marketing',
            'Content Marketing',
            'Email Marketing',
            'Graphic Design',
            'Motion Graphics',
            'Video Editing',
            'Animation',
            'VFX',
            'Photography',
            'Content Writing',
            'Copywriting',
            'Branding',
            'UI Graphics',
            'Finance & Business',
            'Accounting',
            'Finance',
            'Taxation',
            'GST',
            'SAP Finance',
            'SAP MM',
            'Banking',
            'Auditing',
            'Payroll',
            'Financial Analysis',
            'Investment',
            'Insurance',
            'Logistics & Supply Chain',
            'Logistics',
            'Supply Chain',
            'Warehouse Management',
            'Procurement',
            'Purchasing',
            'Inventory Management',
            'Shipping',
            'Freight Forwarding',
            'Marine Logistics',
            'Export & Import',
            'Healthcare',
            'Hospital Administration',
            'Healthcare Management',
            'Medical Coding',
            'Medical Billing',
            'Healthcare Operations',
            'Clinical Administration',
            'Hospitality & Tourism',
            'Hospitality Management',
            'Hotel Management',
            'Front Office',
            'Housekeeping',
            'Food & Beverage',
            'Travel & Tourism',
            'Aviation Ground Staff',
            'Human Resources & Administration',
            'Human Resource',
            'HR Operations',
            'Recruitment',
            'Talent Acquisition',
            'Office Administration',
            'Payroll Administration',
            'Employee Relations',
            'Training & Development',
            'Sales & Customer Support',
            'Sales',
            'Business Development',
            'Inside Sales',
            'Field Sales',
            'Customer Support',
            'Customer Success',
            'Technical Support',
            'Telecalling',
            'Relationship Management',
            'Management',
            'Project Management',
            'Operations Management',
            'Business Management',
            'Product Management',
            'Team Lead',
            'General Management',
            'Education',
            'Trainer',
            'Technical Trainer',
            'Corporate Trainer',
            'Faculty',
            'Instructor',
            'Academic Counselor',
            'Others',
            'Freshers Jobs',
            'Internship',
            'Apprenticeship',
            'Remote Jobs',
            'Work From Home',
            'Government Jobs',
            'Overseas Jobs',
            'Gulf Jobs',
            'UAE Jobs',
            'Freelance',
            'Part-Time',
            'Contract Jobs',
            'Robotics & IoT',
            'Civil & BIM',
            'SAP'
        ];

        // Remove any exact duplicates just in case
        $categories = array_unique($categories);

        foreach ($categories as $category) {
            JobCategory::firstOrCreate(
                ['slug' => Str::slug($category)],
                ['name' => $category]
            );
        }
        
        $this->command->info('Job categories seeded successfully!');
    }
}
